import './globals.css';
import Header from './Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className="mx-auto max-w-7xl min-h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
